name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Getting all dependencies
      run: npm install
    - name: Build FlatLand library
      run: npm run build
